### ISSUE TITLE
РК №1

### ISSUE THREAD

**Issue by edward-grolsh** [frontend-park-mail-ru/2021_2_Frontoviki#4]
[ ] - не понятна разница на форме регистрации между кнопкамми войти и регистрация
<img width="933" alt="Снимок экрана 2021-09-29 в 18 09 02" src="https://user-images.githubusercontent.com/22628783/135296956-71b2aa9f-df6b-4cef-9f85-ea8e960f1243.png">

[ ] - упростить требования к паролю
<img width="421" alt="Снимок экрана 2021-09-29 в 18 09 59" src="https://user-images.githubusercontent.com/22628783/135297119-e6610f10-1abe-4214-8f9f-e3d197f676dd.png">

[ ] - "профиль" выглядит как ссылка кнопка, а действие есть толко на ховер
<img width="654" alt="Снимок экрана 2021-09-29 в 18 11 43" src="https://user-images.githubusercontent.com/22628783/135297495-4d145731-0eba-4226-9ae7-20d7e7ba5ce8.png">

[ ] - кука протухает за минуту

[ ] - не вмержем в мастер пр

[ ] - какой-то неиспользуемый код в папке html storage

[ ] - зачем нужна библиотека в репе, если можно ставить как зависимость или грузить скриптом handlebars

[ ] - не использовать магических заначений
https://github.com/frontend-park-mail-ru/2021_2_Frontoviki/blob/f3213da655fa0ab11bd2fa7a755dea4fcef6537a/public/static/js/content/modal.js#L109

[ ] - заменить на статус код
https://github.com/frontend-park-mail-ru/2021_2_Frontoviki/blob/f3213da655fa0ab11bd2fa7a755dea4fcef6537a/public/static/js/content/modal.js#L123

[ ] - разнести логику авторизации и регистрации
https://github.com/frontend-park-mail-ru/2021_2_Frontoviki/blob/hw3/public/static/js/content/modal.js

[ ] - предкомпилиуремые шаблоны класть в папку билд при сборке скриптом и з package.json

[ ] - настроить авторизацию нормальную

**Comment by Shureks-den** [comment]
Чек-лист исправленний: 
[✓] - заменить на статус код
[✓] - не использовать магических заначений
[✓] - зачем нужна библиотека в репе, если можно ставить как зависимость или грузить скриптом handlebars
[✓] - какой-то неиспользуемый код в папке html storage
[✓] - не вмержем в мастер пр
[✓] - кука протухает за минуту (теперь за час)
[✓] - разнести логику авторизации и регистрации
[✓] - настроить авторизацию нормальную
[✓] - упростить требования к паролю (4 символа)

Нужно еще поправить:
[!] - предкомпилиуремые шаблоны класть в папку билд при сборке скриптом и з package.json (возможно webpack???)
[!] - "профиль" выглядит как ссылка кнопка, а действие есть толко на ховер
[!] - не понятна разница на форме регистрации между кнопкамми войти и регистрация

**Comment by Shureks-den** [comment]
![image](https://user-images.githubusercontent.com/65308659/141656719-b15afedb-3eff-4350-90f5-3b3e02ce83ea.png)
Поменяли модальное окно

**Comment by Shureks-den** [comment]
Пароль от 5 любых символов

**Comment by Shureks-den** [comment]
изменили логику профиля в навбаре - теперь показывается аватар и имя 
![image](https://user-images.githubusercontent.com/65308659/141656748-f2549ddd-0192-4cc9-9f43-bcf8008a52d0.png)

При нажатии в эту область 
открывается меню с действиями 
![image](https://user-images.githubusercontent.com/65308659/141656766-926c2b9b-0fc7-4f4d-84cc-82b6d542afa7.png)

**Comment by Shureks-den** [comment]
https://github.com/frontend-park-mail-ru/2021_2_Frontoviki/blob/dev/public/static/js/modules/autorisation.js
https://github.com/frontend-park-mail-ru/2021_2_Frontoviki/blob/dev/public/static/js/modules/registration.js

Вынесли регистрацию и авторизацию в отдельные модули 
![image](https://user-images.githubusercontent.com/65308659/141656856-c1fd5ae5-6628-469b-93a3-667191c3ea7b.png)

**Comment by Shureks-den** [comment]
![image](https://user-images.githubusercontent.com/65308659/141656895-61e7edb4-08d1-40d1-912a-bcfb5ade16c8.png)
Используем статус-коды

**Comment by Shureks-den** [comment]
Вынесли магические переменные в константы в отдельном файле 
![image](https://user-images.githubusercontent.com/65308659/141656941-272edf82-1b35-48d6-a31c-86c55db363b0.png)

**Comment by Shureks-den** [comment]
Касательно нормальной авторизации - была проблема с http и то что ставили у кук samesite none и гугл их не пропускал. Переехали на https + используем samesite strict.  (с этой проблемой разобрались вместе с Игорем)
